### PR TITLE
Male Combee added back in

### PR DESCRIPTION
**Pull request by osherwott**
Base sprite was changed to female in the official, so you had two female sprites instead of one male and one female

### CODE REVIEW

**Comment by Crobat4** [comment]
Forgot they replaced Combee
Ok, there are two issues

First, you should make a brand new branch using `develop` or `develop-crobat` as base instead using an existing one, and when selecting to which branch you want to merge the new changes into, select any of the those branches, normally `develop-crobat` but depends on which branch did you use as base. I fixed this already.

Second, you shouldn't edit or upload anything from the `/docs` folder.
The `/docs` folder gets automatically updated according to the changes made in the `/src` folder when using `npm run website`, and that command is only used when you are putting the fork in production (like putting it in Github pages), so anything you do there, it may be replaced later.
I need you to revert the changes in that folder since I can't do it by myself apparently, I think `Allow edits and access to secrets by maintainers` needs to be checked.

**Review by Crobat4 — CHANGES_REQUESTED** [review]
This needs to be reverted.

**Review by Crobat4 — CHANGES_REQUESTED** [review]
This needs to be reverted.

**Comment by osherwott** [comment]
Thank you for explaining it so thoroughly! I have successfully reverted the doc changes.

"Allow edits by maintainers" is checked, but don't know why it's different. Perhaps it's because I copied the entire repo? I will stick to branching from "develop" forks from now on.

**Comment by Crobat4** [comment]
Very nice, thanks for the PR.

**Pull request merged**
